# Generated by Django 4.2.21 on 2025-06-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IptalBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mesaj', models.TextField(blank=True)),
                ('rezervasyon_tarihi', models.DateTimeField(blank=True, null=True)),
                ('ucret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
